#!/usr/bin/env bash






nonce=$(openssl rand -hex 16)






##############################################################################################################################





synth() {
    :   #   Quickly test if an interpreter is in forge without cluttering the environments. Use "source ~/port/synth and
        #   then type synth <package> to test the package. This is to see if the package is executable, and the location
        #   for example "synth rust" has no result but "synth rust-script" shows a (synthetic) location. The environment
        #   name is a cryptographic nonce to prevent collisions, and is removed afterwards
        #
        #   For seeing if something is in forge, mamba search is faster
        #
        #   If synth returns a conda env location, the package can likely be used with port if support is added

    local int="$1"
    if [[ ! $int ]]; then echo "no argument"; fi

    mamba create -n $nonce
    mamba activate $nonce
    mamba install -y micromamba pipdeptree $int
    $1 --version
    local loc=$(which $int)
    mamba deactivate
    mamba env remove -y -n $nonce
    echo -e "\n\r[094m    $loc\n[0m"
    echo -e "$loc" >> ~/port/output.txt
}
